 [platformio]
default_envs = m5stack-tab5

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5fire]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip
board = m5stack-fire
framework = arduino
monitor_speed = 115200
lib_deps = 
    M5Unified
build_flags = -DARDUINO_M5STACK_FIRE

[env:m5cores3]
platform = espressif32@6.7.0 
platform_packages =
    ; Force the older framework bundle version (maps to Arduino 2.0.11)
    framework-arduinoespressif32@3.20011.230801 
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    M5Unified @ 0.1.14
build_unflags = 
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_MODE=1
build_flags = 
    -DARDUINO_M5STACK_CORES3
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=1
; temporary port for development    
; monitor_port = COM8
; upload_port = COM8

[env:m5core2]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
lib_deps = 
    M5Core2 @ 0.1.9
    M5Unified @ 0.1.14

[env:teensy41_ili9341]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/kurte/ILI9341_t3n#v1.1.1
build_flags = 
    -DARDUINO_TEENSY41
    -DILI9341

[env:teensy41_ili9488]
platform = teensy@4.17.0
board = teensy41
framework = arduino
monitor_speed = 115200
build_flags = 
    -DARDUINO_TEENSY41
    -DILI9488
; Force specific package versions for 1.57.3 support - otherwise USB keyboard will not work
platform_packages =
    framework-arduinoteensy@~1.157.0
    tool-teensy@<2.0.0

; platformio untested starting here

[env:tdisplays3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
lib_deps = 
    bodmer/TFT_eSPI @ 2.5.43
build_flags = 
    -D ARDUINO_LILYGO_T_DISPLAY_S3
    -D USER_SETUP_ID=206
    ; -D ST7789_DRIVER
    ; -D CGRAM_OFFSET
    ; -D TFT_RGB_ORDER=TFT_BGR
    ; -D TFT_INVERSION_ON
    ; -D TFT_PARALLEL_8_BIT
    ; -D TFT_WIDTH=170
    ; -D TFT_HEIGHT=320
    ; -D TFT_DC=7
    ; -D TFT_RST=5
    ; -D TFT_WR=8
    ; -D TFT_RD=9
    ; -D TFT_D0=39
    ; -D TFT_D1=40
    ; -D TFT_D2=41
    ; -D TFT_D3=42
    ; -D TFT_D4=45
    ; -D TFT_D5=46
    ; -D TFT_D6=47
    ; -D TFT_D7=48
    ; -D TFT_BL=38
    ; -D TFT_BACKLIGHT_ON=HIGH
    ; -D LOAD_GLCD
    ; -D LOAD_FONT2
    ; -D LOAD_FONT4
    ; -D LOAD_FONT6
    ; -D LOAD_FONT7
    ; -D LOAD_FONT8
    ; -D LOAD_GFXFF
    ; -D SMOOTH_FONT
;-D USER_SETUP_LOADED
; -D ARDUINO_USB_CDC_ON_BOOT=0  ; Disable CDC on boot (use UART)
; -D ARDUINO_USB_MODE=0         ; Hardware CDC and JTAG
; + TFT_eSPI @ 2.5.43 with User_Setup_Select.h configured, recommend put in lib folder
; -U ARDUINO_USB_CDC_ON_BOOT
; -U ARDUINO_USB_MODE

[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
build_flags =
  -DARDUINO_LILYGO_T_DISPLAY_S3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DUSER_SETUP_LOADED=1
  -DST7789_DRIVER=1
  -DTFT_WIDTH=170
  -DTFT_HEIGHT=320
  -DTFT_RGB_ORDER=TFT_RGB
  -DTFT_INVERSION_ON=1
  -DTFT_MOSI=11
  -DTFT_SCLK=12
  -DTFT_CS=10
  -DTFT_DC=13
  -DTFT_RST=1
  -DTFT_BL=15
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DLOAD_FONT4=1
  -DSPI_FREQUENCY=27000000
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DARDUINO_USB_MODE=1
lib_deps =
  bodmer/TFT_eSPI @ 2.5.43
; Set flash size to 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
; Use the custom partition table created above
board_build.partitions = partitions_3_9.9.csv

; see README for flash speed and PSRAM speed

[env:sunton7]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
    https://github.com/moononournation/Arduino_GFX#v1.3.1
build_flags = -DARDUINO_SUNTON_8048S070

; planned:

; need to configure new board with PSRAM??? esp. PSRAM speed
[env:atoms3r]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
lib_deps = 
    M5Unified
build_flags = -DARDUINO_M5Stack_ATOMS3R

; cardputer

; m5core basic ???

; tab5
[env:m5stack-tab5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = m5stack-tab5-p4
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D M5TAB5
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I src

lib_deps = 
    M5Stack/M5Unified @ ^0.2.14
    M5Stack/M5GFX @ ^0.2.20
    BLE @ ^3.3.5
    FFat @ ^3.3.5
    SD @ ^3.3.5
    SD_MMC @ ^3.3.5
    SPI @ ^3.3.5
    Wire @ ^3.3.5
    FS @ ^3.3.5
    ; m5stack/M5Touch @ ^0.2.3
    ; m5stack/M5Audio @ ^0.2.3

; development only
monitor_port = COM11
upload_port = COM11

[env:esp32p4_pioarduino]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.20
platform_packages = 
    framework-arduinoespressif32 @ https://github.com
board = esp32-p4-evboard
framework = arduino
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps = 
    https://github.com/M5Stack/M5Unified.git
    https://github.com/M5Stack/M5GFX.git