; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:atoms3]
platform = espressif32
board = m5stack-atoms3
framework = arduino
lib_deps = 
    M5Unified @ ^0.2.15
    WiFi @ ^2.0.0
    Wire @ ^2.0.0
    ESP32 BLE Arduino @ ^2.0.0
build_flags = 
    -DARDUINO_M5Stack_ATOMS3
    -DESP32S3
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
monitor_speed = 115200
upload_speed = 1500000
;temporary use only
; upload_port = COM13
; monitor_port = COM13

[env:stickc]
platform = espressif32
board = m5stick-c
framework = arduino
lib_deps = 
    M5Unified @ ^0.2.15
    WiFi @ ^2.0.0
    Wire @ ^2.0.0
    ESP32 BLE Arduino @ ^2.0.0
build_flags = -D ARDUINO_M5STACK_STICKC -Os
board_build.partitions = partitions_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4063232
monitor_speed = 115200
upload_speed = 1500000
;port for development only
; upload_port = COM4
; monitor_port = COM4

[env:stickcplus]
platform = espressif32
board = m5stick-c
framework = arduino
lib_deps = 
    M5StickCPlus
    WiFi @ ^2.0.0
    Wire @ ^2.0.0
    ESP32 BLE Arduino @ ^2.0.0
build_flags = -D ARDUINO_M5STACK_STICKC -D ARDUINO_M5STACK_STICKCPLUS -Os
board_build.partitions = partitions_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4063232
monitor_speed = 115200
upload_speed = 1500000
;port for development only
; upload_port = COM4
; monitor_port = COM4

[env:m5core-16m]
platform = espressif32
board = m5stack-core-esp32-16M
framework = arduino
monitor_speed = 115200
lib_deps = 
    M5Unified
build_flags = -DARDUINO_M5STACK_CORE
